language: node_js
node_js:
  - '8'
sudo: false
branches:
  except:
    - gh-pages
install:
  - npm install
script:
  - npm test
  - npm run-script updatedb
  - npm run-script updatedb force
env:
  global:
    secure: HyJER2vbLVd8rvfFdZ9XUlIlYPmAtXM2ADXzc1Z6cdzDFXqmZs3Rgh66O7PXAVFkImD8aNWKs6Oc6ZOZzhSQqU8tWvOcq3I9JAKpsKAHZh9wYEhVbiuOFUJlViFzkQDUQY/XzL3lOs3OGpqE/ZiX5xJFOQ2PZoumtXfQ7CiDWmfCTaaWIafgw5/+xgAwLVuGtpQZyPxMz67RAsblS4FN6ISRdE64H1L8fOOSDHW+pv44IuyVftwJhqx1dxyu2AzB5NMA8izqOyTQ2SRv0J9YJea55LUp2H+tMjxr/npsMAh8w1HWGNDoZdI8wNTX0CMICe0HN+LN0OZh3YBOmQABRvuyQNqiorWgdH4w1wS8ij83PaKHipsKwL1+Ez2CcVQkHvXJUNodqCNH2uW9fAeDPrQKj0qLpiVeAXlkvUCpGWW4jSr8e1R4KKndtnsSmBmq91bdKUxWfk//pAmr/klcoi8QtMFqk9ZTpivhfJX8ci4rM00CqdHb/nZarl3gDE08uyNoEuBTmrjH6GLW6pHuUdUqGBLjnq6Jh23OmJDrj3plr3EzvreNVNknu3I7Hzhjdo2FcXh8Apoz48L2TsSxYQCd99f34twZnOfaE54xKAloGHfdAEGpsRsTcvW0IkQ540WKWDWbDm5PdoS7uonIvwctuBfLtkfnU3g/uVsN+44=
